openapi: 3.1.0
info:
  version: 2.0.0
  title: MarineTraffic Inbox API
  termsOfService: https://www.marinetraffic.com/en/p/terms
  contact:
    email: customersupport@marinetraffic.com
    url: https://www.kpler.com/company/contact-us
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://bucket001-jp.s3.ap-northeast-1.amazonaws.com/000001/attachments/2024/3/26/1711445901_image-0-1711445900995.png
  description: >
    This is the document API and examples to demonstrate features of the MarineTraffic Inbox API specification.

    # Introduction

    The MarineTraffic Inbox API is a RESTful API that allows you to interact with the MarineTraffic Inbox platform.

    # Requirements

      - Make sure you have an application following this [guide](https://docs.google.com/document/d/1gOdzz4zYcJ5SVtY4xl-kn3isu04wQdBJHJAAPxoTJTc/edit?usp=sharing)
servers:
  - url: https://endpoint.{domain}
    variables:
      domain:
        default: staging-api.chartdesk.net
        description: domain
paths:
  "/app_api/v1/attachments":
    post:
      tags:
      - Attachments
      summary: Upload an attachment
      description: >
        - Upload an attachment to the server

        - API rate limit is 20 requests per minute
      operationId: uploadAttachment
      security:
      - OAuth2:
        - create_attachment
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Attachment"
        '401':
          description: Unauthorized
        '403':
          description: Invalid scope
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: The raw content of file to upload
                disposition:
                  type: string
                  enum:
                  - inline
                  - attachment
                  - link
              required:
              - file
  "/app_api/v1/me":
    get:
      tags:
      - Me
      summary: Get Myself Information
      description: >
        - Get information of the current user

        - API rate limit is 10 requests per minute
      operationId: getMySelfInformation
      security:
      - OAuth2:
        - read
        - public
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '401':
          description: Unauthorized
  "/app_api/v1/emails":
    post:
      tags:
      - Emails
      summary: Send Email
      description: >
        - Send email via api

        - API rate limit is 10 requests per minute
      operationId: sendEmail
      security:
      - OAuth2:
        - send_mail
        - create_mail
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                    - created
        '401':
          description: Unauthorized
        '403':
          description: Invalid scope
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                subject:
                  type: string
                body:
                  type: string
                body_type:
                  type: string
                  enum:
                  - plain_text
                  - html
                action:
                  type: string
                  enum:
                  - normal
                  - reply
                  - forward
                  - replyall
                to:
                  type: object
                  properties:
                    emails:
                      type: array
                      items:
                        type: string
                      description: array of email address
                    address_group_ids:
                      type: array
                      items:
                        type: string
                      description: address group ids in ChartDesk
                cc:
                  type: object
                  properties:
                    emails:
                      type: array
                      items:
                        type: string
                      description: array of email address
                    address_group_ids:
                      type: array
                      items:
                        type: string
                      description: address group ids in ChartDesk
                bcc:
                  type: object
                  properties:
                    emails:
                      type: array
                      items:
                        type: string
                      description: array of email address
                    address_group_ids:
                      type: array
                      items:
                        type: string
                      description: address group ids in ChartDesk
                attachments:
                  type: array
                  items:
                    type: integer
                  description: array of attachment ids
            examples:
              SimpleEmail:
                value:
                  from: hello@chartdesk.pro
                  body_type: plain_text
                  subject: hello
                  body: Hi there
                  to:
                    emails:
                    - your_emai@email.com
                  cc:
                    emails:
                    - your_cc@email.com
                  action: normal
              EmailWithAttachments:
                value:
                  from: hello@chartdesk.pro
                  body_type: plain_text
                  subject: email with attachments
                  body: Hi there
                  to:
                    emails:
                    - your_emai@email.com
                  cc:
                    emails:
                    - your_cc@email.com
                  action: normal
                  attachments:
                  - 1
                  - 2
  "/app_api/v1/lines":
    get:
      tags:
      - Lines
      summary: Get accessable lines
      description: >
        - Return list of lines which accessable

        - API rate limit is 30 requests per minute
      operationId: getLines
      security:
      - OAuth2:
        - read
        - public
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ArrayOfLine"
        '401':
          description: Unauthorized
  "/app_api/v1/address_books":
    get:
      tags:
      - Address Book
      summary: Get address_books
      description: >
        - Get list address_books

        - API rate limit is 60 requests per minute
      operationId: getAddressBooks
      security:
      - OAuth2:
        - address_books
      parameters:
      - name: page
        in: query
        description: The page of list address_books
        required: false
        explode: true
        schema:
          type: integer
          default: 1
      - name: per_page
        in: query
        description: The number of records per page
        required: false
        explode: true
        schema:
          type: integer
          default: 10
          enum:
          - 10
          - 20
          - 30
          - 40
          - 50
      responses:
        '200':
          description: It will return the list of address_books with page and per_page
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ArrayOfAddressBook"
        '401':
          description: unauthorized
  "/app_api/v1/address_books/{id}":
    get:
      tags:
      - Address Book
      summary: Get detail of AddressBook by ID
      description: >
        - Get detail of AddressBook by ID

        - API rate limit is 300 requests per minute
      operationId: getAddressBookById
      security:
      - OAuth2:
        - address_books
      parameters:
      - name: id
        in: path
        description: This is the id of address_book
        required: true
        schema:
          type: integer
          default: 1
      responses:
        '200':
          description: It returns the address_book
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AddressBook"
        '401':
          description: unauthorized
        '404':
          description: the record is not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://endpoint.staging-api.chartdesk.net/oauth/authorize
          tokenUrl: https://endpoint.staging-api.chartdesk.net/oauth/token
          scopes:
            public: access user info
            send_mail: create and sending email
            read: read user info
            create_attachment: upload attachment
            create_mail: create email
            address_books: access to address_books
  schemas:
    Attachment:
      type: object
      properties:
        id:
          type: integer
        original_file_url:
          type: string
        name:
          type: string
        disposition:
          type: string
          enum:
          - link
          - attachment
          - inline
        size:
          type: integer
        content_type:
          type: string
    User:
      properties:
        id:
          type: integer
        avatar:
          type: string
        name:
          type: string
        departments:
          type: string
        user_name:
          type: string
    Line:
      properties:
        id:
          type: integer
        email:
          type: string
        can_send:
          type: boolean
    ArrayOfLine:
      type: array
      items:
        "$ref": "#/components/schemas/Line"
    AddressBook:
      properties:
        id:
          type: integer
          example: 1
        contact_type:
          type: string
          example: contact
          enum:
          - company
          - department
          - contact
        name:
          type: string
          example: chartdesk
        salutation:
          type: string
          example: hellooooooo babey
        job_title:
          type: string
          example: this is job_title
        email_address_work_1:
          type: string
          example: email_address_work_1@chartdesk.pro
        email_address_work_2:
          type: string
          example: email_address_work_2@chartdesk.pro
        email_address_work_3:
          type: string
          example: email_address_work_3@chartdesk.pro
        email_address_personal_1:
          type: string
          example: email_address_personal_1@chartdesk.pro
        email_address_personal_2:
          type: string
          example: email_address_personal_2@chartdesk.pro
        email_address_personal_3:
          type: string
          example: email_address_personal_3@chartdesk.pro
        email_address_other_1:
          type: string
          example: email_address_other_1@chartdesk.pro
        email_address_other_2:
          type: string
          example: email_address_other_2@chartdesk.pro
        email_address_other_3:
          type: string
          example: email_address_other_3@chartdesk.pro
        phone_mobile_1:
          type: string
          example: "+380 48 7165731"
        phone_mobile_2:
          type: string
          example: "+380 48 7165732"
        phone_mobile_3:
          type: string
          example: "+380 48 7165733"
        phone_office_1:
          type: string
          example: "+380 48 716573"
        phone_office_2:
          type: string
          example: "+380 48 7165732"
        phone_office_3:
          type: string
          example: "+380 48 7165733"
        phone_fax_1:
          type: string
          example: "+380 48 7165731"
        phone_fax_2:
          type: string
          example: "+380 48 7165732"
        phone_fax_3:
          type: string
          example: "+380 48 7165733"
        phone_other_1:
          type: string
          example: "+380 48 7165731"
        phone_other_2:
          type: string
          example: "+380 48 7165732"
        phone_other_3:
          type: string
          example: "+380 48 7165733"
        im:
          type: string
        company:
          type: integer
        department:
          type: integer
        post_address:
          type: string
          example: 1, Leytenanta Shmidta Street UA-65012 Odessa
        city:
          type: string
        state:
          type: string
        country:
          type: string
          example: VietNam
        web_url:
          type: string
          example: https://chartdesk.pro/
        notes:
          type: string
          example: First note Second note
    ArrayOfAddressBook:
      type: array
      items:
        "$ref": "#/components/schemas/AddressBook"
security:
  - OAuth2:
    - public
    - read
