openapi: 3.1.0
info:
  version: 2.0.0
  title: MarineTraffic Inbox API
  termsOfService: https://www.marinetraffic.com/en/p/terms
  contact:
    email: customersupport@marinetraffic.com
    url: https://www.kpler.com/company/contact-us
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://bucket001-jp.s3.ap-northeast-1.amazonaws.com/000001/attachments/2024/3/26/1711445901_image-0-1711445900995.png
  description: >
    This is the document API and examples to demonstrate features of the MarineTraffic Inbox API specification.

    # Introduction

    The MarineTraffic Inbox API is a RESTful API that allows you to interact with the MarineTraffic Inbox platform.

    # Requirements

      - Make sure you have an application following this [guide](https://github.com/chartdesk/api-doc/blob/main/guides/README.md)
servers:
  - url: https://endpoint.{domain}
    variables:
      domain:
        default: staging-api.chartdesk.net
        description: domain
paths:
  '/app_api/v1/attachments':
    $ref: paths/Attachments/attachments.yaml

  '/app_api/v1/me':
    $ref: paths/Me/myself.yaml

  '/app_api/v1/emails':
    $ref: paths/Emails/emails.yaml

  '/app_api/v1/lines':
    $ref: paths/Lines/lines.yaml

  '/app_api/v1/address_books':
    $ref: paths/AddressBooks/address_books.yaml

  '/app_api/v1/address_books/{id}':
    $ref: paths/AddressBooks/address_book_{id}.yaml

components:
  $ref: components/headers/security_schemes/OAuth2.yaml
security:
  - OAuth2:
    - public
    - read
